build: github action

diff --git a/.github/workflows/edXTestSuit.yml b/.github/workflows/edXTestSuit.yml
--- a/.github/workflows/edXTestSuit.yml
+++ b/.github/workflows/edXTestSuit.yml
@@ -23,13 +23,13 @@ jobs:
             runtime: "iOS-14-4"
             device: "iPhone 8"
             task: "testLTRPreviousOS"
-          - name: "Test RTL iOS 13.4"
-            runtime: "iOS-13-4"
-            device: "iPhone 8"
-            task: "testRTLPreviousOS"
+          # - name: "Test RTL iOS 14.4"
+          #   runtime: "iOS-13-4"
+          #   device: "iPhone 8"
+          #   task: "testRTLPreviousOS"
     steps:
-    # - name: Git checkout
-    #   uses: actions/checkout@v2
+    - name: Git checkout
+      uses: actions/checkout@v2
     - name: Link simulator runtimes
       run: |
         sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
@@ -40,20 +40,20 @@ jobs:
         sudo xcode-select -s /Applications/Xcode_13.2.1.app
         xcodebuild -version -sdk
         xcrun simctl list
-    # - name: Run tests
-    #   if: always()
-    #   run: |
-    #     TASK="${{ matrix.env.task }}"
-    #     RUNTIME="${{ matrix.env.runtime }}"
-    #     DEVICE="${{ matrix.env.device }}"
-    #     DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
-    #     RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
-    #     DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
-    #     xcrun simctl boot $DESTINATION_ID
-    #     ./gradlew -q $TASK | xcpretty -c
-    #     if [[ $? -eq 0 ]]; then
-    #     echo "Tests passed!" >&2
-    #     else
-    #     echo "Tests failed!" >&2
-    #     fi
+    - name: Run tests
+      if: always()
+      run: |
+        TASK="${{ matrix.env.task }}"
+        RUNTIME="${{ matrix.env.runtime }}"
+        DEVICE="${{ matrix.env.device }}"
+        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
+        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
+        DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
+        xcrun simctl boot $DESTINATION_ID
+        ./gradlew -q $TASK | xcpretty -c
+        if [[ $? -eq 0 ]]; then
+        echo "Tests passed!" >&2
+        else
+        echo "Tests failed!" >&2
+        fi
       shell: bash
